package com.springmvc.ejercicio4;

import java.util.ArrayList;

public class GestorSeries {
	public ArrayList<Serie> getSeries(){
		ArrayList<Serie> series = new ArrayList<Serie>();
		series.add(new Serie("La casa de papel", "Un misterioso personaje, que se hace llamar \"El Profesor\", planea el mayor de los atracos jamás ideado. Para llevar a cabo el ambicioso plan, recluta a una banda formada por personas con ciertas cualidades y algo en común: no tienen nada que perder. El objetivo es atracar la Fábrica Nacional de Moneda y Timbre, con la intención de quedarse encerrados dentro con una misión muy concreta: no robar dinero, sino crearlo...", 2017, 5, "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQNdx73i9ubLbzc-lv_ornnZ1R6Ms0dy2zmcJvMxays0nYtKbKY"));
		series.add(new Serie("Arcane", "La trama de Arcane: League of Legends está ambientada en el pasado. Contada como una historia de origen, nos presenta el conflicto existente entre dos ciudades, Piltover y Zaun; ambas pertenecientes al mundo de Runaterra. ... La rivalidad entre estas dos ciudades divide incluso a familias y amigos.", 2021, 1, "https://i.blogs.es/f95af1/arc1_characterposterjinx-4-5/450_1000.png"));
		series.add(new Serie("Cobra Kai", "30 años después de su enfrentamiento final en el torneo de kárate 'All Valley', Johnny Lawrence (William Zabka) está en un mal momento de su vida. Sin embargo, tras ayudar a Miguel (Xolo Maridueña), un chico que sufre bullying, Johnny decide volver a abrir el dojo 'Cobra Kai'. El problema es que esto vuelve a desatar la rivalidad con Daniel LaRusso (Ralph Macchio), que ahora es un hombre de negocios felizmente casado, pero al que le falta algo tras la muerte de su mentor, el Sr. Miyagi.", 2018, 4, "https://hips.hearstapps.com/es.h-cdn.co/fotoes/images/series-television/karate-kid-serie-youtube-red/136710092-1-esl-ES/Vuelve-Karate-Kid-!en-forma-de-serie.png"));
		series.add(new Serie("El juego del calamar", "Cientos de jugadores con problemas económicos aceptan una extraña invitación para competir en juegos infantiles. Dentro les esperan un premio tentador y desafíos letales.", 2021, 1, "squid.jpg"));
		series.add(new Serie("El método Kominsky", "Una comedia dramática sobre un veterano actor, Sandy (Michael Douglas), cuya carrera nunca llegó a funcionar del todo, y que se gana la vida dando clases de interpretación, y su agente Norman (Alan Arkin), recientemente enviudado y muy pesimista con todo lo que le rodea... Del creador de 'Big Bang' y 'Dos hombres y medio'.", 2018, 3, "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRY2DZRAjq3pRTnqYAPyh7k0U9KBWPH2fwEuA42meLLiWQVhg2S"));
		series.add(new Serie("El tiempo que te doy", "Cuenta la superación de una ruptura en diez episodios de escasos minutos, en donde una chica intenta olvidar un amor del pasado. Lina está empezando de nuevo, se muda de casa, busca un nuevo trabajo y prueba nuevas experiencias. Pero lo que Lina intenta hacer en realidad es olvidar un amor del pasado, su primer amor. Cada día, Lina intenta que el tiempo que pasa pensando en Nico sea un minuto menos, para así poder avanzar con su vida.", 2021, 1, "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSNcby3vk7gPu-3LJTsNN64PddLwSQ380rWFbHWo3qLKydl5J5H"));
		series.add(new Serie("El vecino", "A Javier no le van demasiado bien las cosas. Apenas llega a fin de mes con un trabajo precario, y su relación con Lola no va precisamente bien. Lo que menos necesitaba es que un extraterrestre le cayera encima y le pasara sus superpoderes antes de morir.", 2019, 2, "https://i.blogs.es/3a8826/el-vecino/1366_2000.jpeg"));
		series.add(new Serie("Élite: Historias breves", "Las historias tienen lugar durante el verano antes del inicio del nuevo año en Las Encinas. En las cuatro historias, se explorarán diferentes tramas individuales y conjuntas de algunos de los estudiantes más veteranos de Las Encinas y quizás de los más nuevos, revelando lo que han sido en el último verano antes de comenzar su nuevo año escolar.", 2021, 1, "https://es.web.img3.acsta.net/r_1280_720/pictures/19/08/20/09/33/5389096.jpg"));
		series.add(new Serie("Hache", "Inspirada en hechos reales, Hache narra la historia de una mujer, Helena (Adriana Ugarte) catapultada a la jefatura del tráfico de heroína en la Barcelona de los años 60.", 2019, 2, "https://i.blogs.es/22d96e/hache/650_1200.jpeg"));
		series.add(new Serie("Halston", "Miniserie inspirada en el famoso diseñador de moda y socialité norteamericano Roy Halston Frowick, más conocido como Halston, icono de la moda que ayudó a definir el estilo de los años 70. La serie narra cómo convirtió su nombre inventado en un emporio mundial sinónimo de lujo, sexo, estatus y fama, definiendo literalmente su época -el Nueva York de los años 70 y 80- hasta que una OPA hostil le obligó a luchar por su bien más preciado: Halston.", 2021, 1, "https://culturamania.com/wp-content/uploads/2021/04/unnamed-2-724x1024.png"));
		series.add(new Serie("La asistenta", "Una madre soltera hace trabajos domésticos para llegar a fin de mes mientras lucha contra la indigencia y la burocracia.", 2021, 1, "https://1.bp.blogspot.com/-0nZx5vHMjRQ/YX1ytemhq-I/AAAAAAABYew/qgCGgjvP7lAydIkLHPt1uWynds174YhnQCLcBGAsYHQ/s1080/0523796.jpg-r_1920_1080-f_jpg-q_x-xxyxx.jpg"));
		return series;
	}
}